# -*- mode:toml; -*-
[module.mcconf-makefile]
    extrafiles = [ "mako_Makefile" ]

[module.mcconf-tool]
    extrafiles = [ "mako_mcconf.db", "mako_mcconf" ]


[module.bochs-emu-amd64]
    extrafiles = [ "mako_bochs.rc" ]
