#!/bin/bash

pushd `dirname $0` > /dev/null

#pip install --upgrade pip
pip install -t ./python-libs pydot
pip install -t ./python-libs pydotplus
pip install -t ./python-libs pytoml==0.1.2
pip install -t ./python-libs mako
pip install -t ./python-libs argparse
pip install -t ./python-libs pyparsing
pip install -t ./python-libs pathlib2

popd > /dev/null
